name: Run Tests

on: push

jobs:
  build:

    name: "${{ matrix.bot }} (${{ matrix.dart-version }}/${{ matrix.code-version }}/${{ matrix.os }})"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        node-version: [10]
        dart-version: [stable, dev]
        # for now, code-version will mirror dart-version to reduce number of bots
        # code-version: [stable] #, insiders]
        bot: [dart, flutter, misc]
        include:
          - dart-version: stable
            flutter-version: stable
            code-version: stable
          - dart-version: dev
            flutter-version: dev
            code-version: insiders

    steps:

      - uses: actions/checkout@v1
        
      - name: Setup Node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci
        run: npm ci
        
      - name: Store NPM logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: npm-logs-${{ matrix.os }}
          path: C:\npm\cache\_logs

